package org.autogenerated.rest.artificial.cs.n5sparseshown.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface PGAduRepository extends CrudRepository<PGAduEntity, Integer> {}
