package org.autogenerated.rest.artificial.cs.n5sparseshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5sparseshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "YQQIq")
public class YQQIqEntity {
  public YQQIqEntity() {}

  public YQQIqEntity(Integer id_var, String name_var, Integer value_var, DioO1Entity dioO1_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.dioO1 = dioO1_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private DioO1Entity dioO1;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setDioO1(DioO1Entity dioO1) {
    this.dioO1 = dioO1;
  }

  public DioO1Entity getDioO1() {
    return this.dioO1;
  }

  public YQQIq getDto() {
    YQQIq dto = new YQQIq();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.dioO1Id = this.getDioO1().getId();
    return dto;
  }
}
