package org.autogenerated.rest.artificial.cs.n5densepdhide.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5densepdhide.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "ONVqF")
public class ONVqFEntity {
  public ONVqFEntity() {}

  public ONVqFEntity(
      Integer id_var,
      String name_var,
      Integer value_var,
      NGgCHEntity nGgCH_var,
      WXTGlEntity wXTGl_var,
      E3gJvEntity ownedE3gJv_var,
      UXlnYEntity ownedUXlnY_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.nGgCH = nGgCH_var;
    this.wXTGl = wXTGl_var;
    this.ownedE3gJv = ownedE3gJv_var;
    this.ownedUXlnY = ownedUXlnY_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private NGgCHEntity nGgCH;
  @NotNull @OneToOne private WXTGlEntity wXTGl;

  @NotNull
  @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
  private E3gJvEntity ownedE3gJv;

  @NotNull
  @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
  private UXlnYEntity ownedUXlnY;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setNGgCH(NGgCHEntity nGgCH) {
    this.nGgCH = nGgCH;
  }

  public NGgCHEntity getNGgCH() {
    return this.nGgCH;
  }

  public void setWXTGl(WXTGlEntity wXTGl) {
    this.wXTGl = wXTGl;
  }

  public WXTGlEntity getWXTGl() {
    return this.wXTGl;
  }

  public void setOwnedE3gJv(E3gJvEntity ownedE3gJv) {
    this.ownedE3gJv = ownedE3gJv;
  }

  public E3gJvEntity getOwnedE3gJv() {
    return this.ownedE3gJv;
  }

  public void setOwnedUXlnY(UXlnYEntity ownedUXlnY) {
    this.ownedUXlnY = ownedUXlnY;
  }

  public UXlnYEntity getOwnedUXlnY() {
    return this.ownedUXlnY;
  }

  public ONVqF getDto() {
    ONVqF dto = new ONVqF();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.nGgCHId = this.getNGgCH().getId();
    dto.wXTGlId = this.getWXTGl().getId();
    dto.e3gJvId = this.getOwnedE3gJv().getId();
    dto.e3gJvName = this.getOwnedE3gJv().getName();
    dto.e3gJvValue = this.getOwnedE3gJv().getValue();
    dto.uXlnYId = this.getOwnedUXlnY().getId();
    dto.uXlnYName = this.getOwnedUXlnY().getName();
    dto.uXlnYValue = this.getOwnedUXlnY().getValue();
    return dto;
  }
}
