package org.autogenerated.rest.artificial.cs.n5densepdhide.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface UXlnYRepository extends CrudRepository<UXlnYEntity, Integer> {}
