package org.autogenerated.rest.artificial.cs.n5denseshown.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface RiT1iRepository extends CrudRepository<RiT1iEntity, Integer> {}
