package org.autogenerated.rest.artificial.cs.n5denseshown.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface YD7VbRepository extends CrudRepository<YD7VbEntity, Integer> {}
