package org.autogenerated.rest.artificial.cs.n5denseshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5denseshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "YD7Vb")
public class YD7VbEntity {
  public YD7VbEntity() {}

  public YD7VbEntity(
      Integer id_var,
      String name_var,
      Integer value_var,
      AS7ExEntity aS7Ex_var,
      SIth8Entity sIth8_var,
      RiT1iEntity ownedRiT1i_var,
      IqYSoEntity ownedIqYSo_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.aS7Ex = aS7Ex_var;
    this.sIth8 = sIth8_var;
    this.ownedRiT1i = ownedRiT1i_var;
    this.ownedIqYSo = ownedIqYSo_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private AS7ExEntity aS7Ex;
  @NotNull @OneToOne private SIth8Entity sIth8;

  @NotNull
  @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
  private RiT1iEntity ownedRiT1i;

  @NotNull
  @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
  private IqYSoEntity ownedIqYSo;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setAS7Ex(AS7ExEntity aS7Ex) {
    this.aS7Ex = aS7Ex;
  }

  public AS7ExEntity getAS7Ex() {
    return this.aS7Ex;
  }

  public void setSIth8(SIth8Entity sIth8) {
    this.sIth8 = sIth8;
  }

  public SIth8Entity getSIth8() {
    return this.sIth8;
  }

  public void setOwnedRiT1i(RiT1iEntity ownedRiT1i) {
    this.ownedRiT1i = ownedRiT1i;
  }

  public RiT1iEntity getOwnedRiT1i() {
    return this.ownedRiT1i;
  }

  public void setOwnedIqYSo(IqYSoEntity ownedIqYSo) {
    this.ownedIqYSo = ownedIqYSo;
  }

  public IqYSoEntity getOwnedIqYSo() {
    return this.ownedIqYSo;
  }

  public YD7Vb getDto() {
    YD7Vb dto = new YD7Vb();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.aS7ExId = this.getAS7Ex().getId();
    dto.sIth8Id = this.getSIth8().getId();
    dto.riT1iId = this.getOwnedRiT1i().getId();
    dto.riT1iName = this.getOwnedRiT1i().getName();
    dto.riT1iValue = this.getOwnedRiT1i().getValue();
    dto.iqYSoId = this.getOwnedIqYSo().getId();
    dto.iqYSoName = this.getOwnedIqYSo().getName();
    dto.iqYSoValue = this.getOwnedIqYSo().getValue();
    return dto;
  }
}
