package org.autogenerated.rest.artificial.cs.n5densepdshown.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface B8v25Repository extends CrudRepository<B8v25Entity, Integer> {}
