package org.autogenerated.rest.artificial.cs.n5sparsepdhide.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5sparsepdhide.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "Ye7de")
public class Ye7deEntity {
  public Ye7deEntity() {}

  public Ye7deEntity(Integer id_var, String name_var, Integer value_var, XPvzdEntity xPvzd_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.xPvzd = xPvzd_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private XPvzdEntity xPvzd;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setXPvzd(XPvzdEntity xPvzd) {
    this.xPvzd = xPvzd;
  }

  public XPvzdEntity getXPvzd() {
    return this.xPvzd;
  }

  public Ye7de getDto() {
    Ye7de dto = new Ye7de();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.xPvzdId = this.getXPvzd().getId();
    return dto;
  }
}
