package org.autogenerated.rest.artificial.cs.n5sparsepdhide.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface Ye7deRepository extends CrudRepository<Ye7deEntity, Integer> {}
