package org.autogenerated.rest.artificial.cs.n5denseshown.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/** automatically created on 2020-01-14 */
@ApiModel
public class YD7Vb {
  public YD7Vb() {}

  public YD7Vb(
      Integer id_var,
      String name_var,
      Integer value_var,
      Integer aS7ExId_var,
      Integer sIth8Id_var,
      Integer riT1iId_var,
      Integer iqYSoId_var,
      String riT1iName_var,
      Integer riT1iValue_var,
      String iqYSoName_var,
      Integer iqYSoValue_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.aS7ExId = aS7ExId_var;
    this.sIth8Id = sIth8Id_var;
    this.riT1iId = riT1iId_var;
    this.iqYSoId = iqYSoId_var;
    this.riT1iName = riT1iName_var;
    this.riT1iValue = riT1iValue_var;
    this.iqYSoName = iqYSoName_var;
    this.iqYSoValue = iqYSoValue_var;
  }

  @ApiModelProperty(required = true)
  public Integer id;

  @ApiModelProperty(required = true)
  public String name;

  @ApiModelProperty(required = true)
  public Integer value;

  @ApiModelProperty(required = true)
  public Integer aS7ExId;

  @ApiModelProperty(required = true)
  public Integer sIth8Id;

  @ApiModelProperty(required = true)
  public Integer riT1iId;

  @ApiModelProperty(required = true)
  public Integer iqYSoId;

  @ApiModelProperty(required = true)
  public String riT1iName;

  @ApiModelProperty(required = true)
  public Integer riT1iValue;

  @ApiModelProperty(required = true)
  public String iqYSoName;

  @ApiModelProperty(required = true)
  public Integer iqYSoValue;
}
