package org.autogenerated.rest.artificial.cs.n5mediumpdshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumpdshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "HGss7")
public class HGss7Entity {
  public HGss7Entity() {}

  public HGss7Entity(Integer id_var, String name_var, Integer value_var, S5htzEntity s5htz_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.s5htz = s5htz_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private S5htzEntity s5htz;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setS5htz(S5htzEntity s5htz) {
    this.s5htz = s5htz;
  }

  public S5htzEntity getS5htz() {
    return this.s5htz;
  }

  public HGss7 getDto() {
    HGss7 dto = new HGss7();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.s5htzId = this.getS5htz().getId();
    return dto;
  }
}
