package org.autogenerated.rest.artificial.cs.n5mediumpdshown.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface I4AFGRepository extends CrudRepository<I4AFGEntity, Integer> {}
