package org.autogenerated.rest.artificial.cs.n5mediumpdshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumpdshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "S5htz")
public class S5htzEntity {
  public S5htzEntity() {}

  public S5htzEntity(Integer id_var, String name_var, Integer value_var, I4AFGEntity i4AFG_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.i4AFG = i4AFG_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private I4AFGEntity i4AFG;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setI4AFG(I4AFGEntity i4AFG) {
    this.i4AFG = i4AFG;
  }

  public I4AFGEntity getI4AFG() {
    return this.i4AFG;
  }

  public S5htz getDto() {
    S5htz dto = new S5htz();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.i4AFGId = this.getI4AFG().getId();
    return dto;
  }
}
