package org.autogenerated.rest.artificial.cs.n5mediumpdshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumpdshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "Yag8e")
public class Yag8eEntity {
  public Yag8eEntity() {}

  public Yag8eEntity(Integer id_var, String name_var, Integer value_var, HGss7Entity hGss7_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.hGss7 = hGss7_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private HGss7Entity hGss7;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setHGss7(HGss7Entity hGss7) {
    this.hGss7 = hGss7;
  }

  public HGss7Entity getHGss7() {
    return this.hGss7;
  }

  public Yag8e getDto() {
    Yag8e dto = new Yag8e();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.hGss7Id = this.getHGss7().getId();
    return dto;
  }
}
