package org.autogenerated.rest.artificial.cs.n5mediumshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "CcE0a")
public class CcE0aEntity {
  public CcE0aEntity() {}

  public CcE0aEntity(Integer id_var, String name_var, Integer value_var, RoGagEntity roGag_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.roGag = roGag_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private RoGagEntity roGag;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setRoGag(RoGagEntity roGag) {
    this.roGag = roGag;
  }

  public RoGagEntity getRoGag() {
    return this.roGag;
  }

  public CcE0a getDto() {
    CcE0a dto = new CcE0a();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.roGagId = this.getRoGag().getId();
    return dto;
  }
}
