package org.autogenerated.rest.artificial.cs.n5mediumshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "RoGag")
public class RoGagEntity {
  public RoGagEntity() {}

  public RoGagEntity(Integer id_var, String name_var, Integer value_var, WdL1QEntity wdL1Q_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.wdL1Q = wdL1Q_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private WdL1QEntity wdL1Q;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setWdL1Q(WdL1QEntity wdL1Q) {
    this.wdL1Q = wdL1Q;
  }

  public WdL1QEntity getWdL1Q() {
    return this.wdL1Q;
  }

  public RoGag getDto() {
    RoGag dto = new RoGag();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.wdL1QId = this.getWdL1Q().getId();
    return dto;
  }
}
