package org.autogenerated.rest.artificial.cs.n5mediumshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "WdL1Q")
public class WdL1QEntity {
  public WdL1QEntity() {}

  public WdL1QEntity(Integer id_var, String name_var, Integer value_var, LIM1ZEntity lIM1Z_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.lIM1Z = lIM1Z_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private LIM1ZEntity lIM1Z;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setLIM1Z(LIM1ZEntity lIM1Z) {
    this.lIM1Z = lIM1Z;
  }

  public LIM1ZEntity getLIM1Z() {
    return this.lIM1Z;
  }

  public WdL1Q getDto() {
    WdL1Q dto = new WdL1Q();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.lIM1ZId = this.getLIM1Z().getId();
    return dto;
  }
}
