package org.autogenerated.rest.artificial.cs.n5sparsehide.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5sparsehide.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "M4KNg")
public class M4KNgEntity {
  public M4KNgEntity() {}

  public M4KNgEntity(Integer id_var, String name_var, Integer value_var, PtjWCEntity ptjWC_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.ptjWC = ptjWC_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private PtjWCEntity ptjWC;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setPtjWC(PtjWCEntity ptjWC) {
    this.ptjWC = ptjWC;
  }

  public PtjWCEntity getPtjWC() {
    return this.ptjWC;
  }

  public M4KNg getDto() {
    M4KNg dto = new M4KNg();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.ptjWCId = this.getPtjWC().getId();
    return dto;
  }
}
