package org.autogenerated.rest.artificial.cs.n5sparsehide.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface PtjWCRepository extends CrudRepository<PtjWCEntity, Integer> {}
