package org.autogenerated.rest.artificial.cs.n5densepdhide.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/** automatically created on 2020-01-14 */
@ApiModel
public class ONVqF {
  public ONVqF() {}

  public ONVqF(
      Integer id_var,
      String name_var,
      Integer value_var,
      Integer nGgCHId_var,
      Integer wXTGlId_var,
      Integer e3gJvId_var,
      Integer uXlnYId_var,
      String e3gJvName_var,
      Integer e3gJvValue_var,
      String uXlnYName_var,
      Integer uXlnYValue_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.nGgCHId = nGgCHId_var;
    this.wXTGlId = wXTGlId_var;
    this.e3gJvId = e3gJvId_var;
    this.uXlnYId = uXlnYId_var;
    this.e3gJvName = e3gJvName_var;
    this.e3gJvValue = e3gJvValue_var;
    this.uXlnYName = uXlnYName_var;
    this.uXlnYValue = uXlnYValue_var;
  }

  @ApiModelProperty(required = true)
  public Integer id;

  @ApiModelProperty(required = true)
  public String name;

  @ApiModelProperty(required = true)
  public Integer value;

  @ApiModelProperty(required = true)
  public Integer nGgCHId;

  @ApiModelProperty(required = true)
  public Integer wXTGlId;

  @ApiModelProperty(required = true)
  public Integer e3gJvId;

  @ApiModelProperty(required = true)
  public Integer uXlnYId;

  @ApiModelProperty(required = true)
  public String e3gJvName;

  @ApiModelProperty(required = true)
  public Integer e3gJvValue;

  @ApiModelProperty(required = true)
  public String uXlnYName;

  @ApiModelProperty(required = true)
  public Integer uXlnYValue;
}
