package org.autogenerated.rest.artificial.cs.n5mediumpdhide.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumpdhide.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "BrZFY")
public class BrZFYEntity {
  public BrZFYEntity() {}

  public BrZFYEntity(Integer id_var, String name_var, Integer value_var, RpZ1MEntity rpZ1M_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.rpZ1M = rpZ1M_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private RpZ1MEntity rpZ1M;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setRpZ1M(RpZ1MEntity rpZ1M) {
    this.rpZ1M = rpZ1M;
  }

  public RpZ1MEntity getRpZ1M() {
    return this.rpZ1M;
  }

  public BrZFY getDto() {
    BrZFY dto = new BrZFY();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.rpZ1MId = this.getRpZ1M().getId();
    return dto;
  }
}
