package org.autogenerated.rest.artificial.cs.n5mediumpdhide.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface Fy6u2Repository extends CrudRepository<Fy6u2Entity, Integer> {}
