package org.autogenerated.rest.artificial.cs.n5sparsepdshown.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5sparsepdshown.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "Vvchd")
public class VvchdEntity {
  public VvchdEntity() {}

  public VvchdEntity(Integer id_var, String name_var, Integer value_var, Nf51XEntity nf51X_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.nf51X = nf51X_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private Nf51XEntity nf51X;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setNf51X(Nf51XEntity nf51X) {
    this.nf51X = nf51X;
  }

  public Nf51XEntity getNf51X() {
    return this.nf51X;
  }

  public Vvchd getDto() {
    Vvchd dto = new Vvchd();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.nf51XId = this.getNf51X().getId();
    return dto;
  }
}
