package org.autogenerated.rest.artificial.cs.n5sparsepdshown.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface XC8mARepository extends CrudRepository<XC8mAEntity, Integer> {}
