package org.autogenerated.rest.artificial.cs.n5mediumhide.entity;

import javax.persistence.*;
import javax.validation.constraints.*;
import org.autogenerated.rest.artificial.cs.n5mediumhide.dto.*;
/** automatically created on 2020-01-14 */
@Entity
@Table(name = "HErqD")
public class HErqDEntity {
  public HErqDEntity() {}

  public HErqDEntity(Integer id_var, String name_var, Integer value_var, XpOCtEntity xpOCt_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.xpOCt = xpOCt_var;
  }

  @Id @NotNull private Integer id;
  @NotNull private String name;
  @NotNull private Integer value;
  @NotNull @OneToOne private XpOCtEntity xpOCt;

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setValue(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public void setXpOCt(XpOCtEntity xpOCt) {
    this.xpOCt = xpOCt;
  }

  public XpOCtEntity getXpOCt() {
    return this.xpOCt;
  }

  public HErqD getDto() {
    HErqD dto = new HErqD();
    dto.id = this.getId();
    dto.name = this.getName();
    dto.value = this.getValue();
    dto.xpOCtId = this.getXpOCt().getId();
    return dto;
  }
}
