package org.autogenerated.rest.artificial.cs.n5mediumhide.entity;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
/** automatically created on 2020-01-14 */
@Repository
public interface VIL0SRepository extends CrudRepository<VIL0SEntity, Integer> {}
