package org.autogenerated.rest.artificial.cs.n5densepdshown.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/** automatically created on 2020-01-14 */
@ApiModel
public class UEear {
  public UEear() {}

  public UEear(
      Integer id_var,
      String name_var,
      Integer value_var,
      Integer b8v25Id_var,
      Integer iUJWoId_var,
      Integer oEXmzId_var,
      Integer w27dtId_var,
      String oEXmzName_var,
      Integer oEXmzValue_var,
      String w27dtName_var,
      Integer w27dtValue_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.b8v25Id = b8v25Id_var;
    this.iUJWoId = iUJWoId_var;
    this.oEXmzId = oEXmzId_var;
    this.w27dtId = w27dtId_var;
    this.oEXmzName = oEXmzName_var;
    this.oEXmzValue = oEXmzValue_var;
    this.w27dtName = w27dtName_var;
    this.w27dtValue = w27dtValue_var;
  }

  @ApiModelProperty(required = true)
  public Integer id;

  @ApiModelProperty(required = true)
  public String name;

  @ApiModelProperty(required = true)
  public Integer value;

  @ApiModelProperty(required = true)
  public Integer b8v25Id;

  @ApiModelProperty(required = true)
  public Integer iUJWoId;

  @ApiModelProperty(required = true)
  public Integer oEXmzId;

  @ApiModelProperty(required = true)
  public Integer w27dtId;

  @ApiModelProperty(required = true)
  public String oEXmzName;

  @ApiModelProperty(required = true)
  public Integer oEXmzValue;

  @ApiModelProperty(required = true)
  public String w27dtName;

  @ApiModelProperty(required = true)
  public Integer w27dtValue;
}
