package org.autogenerated.rest.artificial.cs.n5densehide.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
/** automatically created on 2020-01-14 */
@ApiModel
public class Hvltg {
  public Hvltg() {}

  public Hvltg(
      Integer id_var,
      String name_var,
      Integer value_var,
      Integer yaDPDId_var,
      Integer kuGn6Id_var,
      Integer nSPiiId_var,
      Integer wUaJGId_var,
      String nSPiiName_var,
      Integer nSPiiValue_var,
      String wUaJGName_var,
      Integer wUaJGValue_var) {
    this.id = id_var;
    this.name = name_var;
    this.value = value_var;
    this.yaDPDId = yaDPDId_var;
    this.kuGn6Id = kuGn6Id_var;
    this.nSPiiId = nSPiiId_var;
    this.wUaJGId = wUaJGId_var;
    this.nSPiiName = nSPiiName_var;
    this.nSPiiValue = nSPiiValue_var;
    this.wUaJGName = wUaJGName_var;
    this.wUaJGValue = wUaJGValue_var;
  }

  @ApiModelProperty(required = true)
  public Integer id;

  @ApiModelProperty(required = true)
  public String name;

  @ApiModelProperty(required = true)
  public Integer value;

  @ApiModelProperty(required = true)
  public Integer yaDPDId;

  @ApiModelProperty(required = true)
  public Integer kuGn6Id;

  @ApiModelProperty(required = true)
  public Integer nSPiiId;

  @ApiModelProperty(required = true)
  public Integer wUaJGId;

  @ApiModelProperty(required = true)
  public String nSPiiName;

  @ApiModelProperty(required = true)
  public Integer nSPiiValue;

  @ApiModelProperty(required = true)
  public String wUaJGName;

  @ApiModelProperty(required = true)
  public Integer wUaJGValue;
}
